app/items/models/__init__.py
from .item import *
from .item_like import *
from .item_comment import *

app/items/models/item.py
from urllib.parse import urlparse

from django.contrib.auth import get_user_model
from django.core.files import File
from django.db import models

from core.models import TimeStampedModel
from utils.check_url_from_url_parser import CheckURL
from utils.file import download, get_buffer_ext
from ..models.managers import ItemManager

User = get_user_model()

__all__ = (
    'Item',
)


class Item(TimeStampedModel):
    CATEGORY_A = 'a'
    CATEGORY_B = 'b'
    CATEGORY_C = 'c'
    CATEGORY_D = 'd'
    CATEGORY_E = 'e'
    CATEGORY_F = 'f'
    CATEGORY_G = 'g'
    CATEGORY_H = 'h'
    CATEGORY_I = 'i'
    CATEGORY_J = 'j'
    CATEGORY_K = 'k'
    CHOICES_CATEGORY = (
        (CATEGORY_A, '패션의류/잡화'),
        (CATEGORY_B, '유아용품'),
        (CATEGORY_C, '뷰티'),
        (CATEGORY_D, '주방/생활용품'),
        (CATEGORY_E, '디지털/가전제품'),
        (CATEGORY_F, '가구/인테리어'),
        (CATEGORY_G, '운동용품'),
        (CATEGORY_H, '여행'),
        (CATEGORY_I, '도서/음반/공연'),
        (CATEGORY_J, '자동차용품'),
        (CATEGORY_K, '기타'),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='user_items'
    )
    name = models.CharField('상품명', max_length=50)
    purchase_url = models.URLField('상품 URL', max_length=400, blank=True)
    price = models.IntegerField('상품 가격')
    category = models.CharField('상품 카테고리', max_length=100, choices=CHOICES_CATEGORY, blank=False)
    img = models.ImageField('상품 이미지', upload_to='items', blank=True)
    public_visibility = models.BooleanField('공개 여부', default=True)
    is_purchase = models.BooleanField('구매 여부', default=False)
    purchase_date = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    like_users = models.ManyToManyField(
        User,
        through='ItemLike',
        related_name='like_items',
        blank=True
    )

    objects = ItemManager()

    class Meta:
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        if Item.objects.filter(pk=self.pk):
            super().save()
        else:
            if self.purchase_url and not self.img:
                url = self.purchase_url
                search_result = CheckURL(url)
                search_result.check_url_from_parser()

                item_img_url = search_result.item_data.item_img
                if item_img_url:
                    temp_file = download(item_img_url)
                    file_name = '{urlparse}.{ext}'.format(
                        urlparse=urlparse(item_img_url).path.split('/')[-1].split('.')[0],
                        ext=get_buffer_ext(temp_file)
                    )
                    self.purchase_url = search_result.item_data.url
                    self.img.save(file_name, File(temp_file))
            super().save()

    def __str__(self):
        return f'{self.pk}. {self.name} - {self.user}'

app/items/models/item_comment.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import TimeStampedModel
from . import Item

User = get_user_model()

__all__ = (
    'ItemComment',
)


class ItemCommentManager(models.Manager):
    def no_reply_all(self):
        queryset = self.filter(parent=None)
        return queryset


class ItemComment(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    item = models.ForeignKey(Item, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField('')
    parent = models.ForeignKey('self', blank=True, null=True, related_name='replies', on_delete=models.CASCADE)

    objects = ItemCommentManager()

    class Meta:
        ordering = ['created_time']

    def children(self):
        return ItemComment.objects.filter(parent=self)

    def __str__(self):
        return f'{self.pk}. {self.content} - {self.user}'

app/items/forms.py
from django import forms

from .models import Item, ItemComment

__all__ = (
    'ItemForm',
    'CommentForm',
)


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            'name',
            'purchase_url',
            'price',
            'category',
            'img',
            'public_visibility',
        )

    def save(self, commit=True, *args, **kwargs):
        if not self.instance.pk and commit:
            user = kwargs.pop('user', None)
            if not user:
                raise ValueError('User field is required')
            self.instance.user = user

        return super().save(*args, **kwargs)


class CommentForm(forms.ModelForm):
    class Meta:
        model = ItemComment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': "댓글을 입력해주세요",
                }
            )
        }

app/items/apis/__init__.py
from .comment import *
from .item import *
from .like import *

app/items/urls/views.py
from django.urls import path
from .. import views

app_name = 'items'
urlpatterns = [
    path('list/', views.my_item_list, name='my-item-list'),
    path('list/<int:item_pk>/', views.item_detail, name='item-detail'),
    path('list/<int:item_pk>/edit/', views.item_edit, name='item-edit'),
    path('delete/', views.item_delete, name='item-delete'),

    # search
    path('search/', views.search_url, name='search-url'),
    path('search/add/', views.item_add, name='item-add'),

    # complete
    path('complete/', views.purchase_complete, name='purchase-complete'),
    path('complete/list/', views.my_complete_item_list, name='my-complete-item-list'),
    path('complete/list/<int:item_pk>/', views.purchase_item_detail, name='purchase-item-detail'),

    # public
    path('public/<int:item_pk>/', views.public_item_detail, name='public-item-detail'),
    path('public/add/', views.add_from_public, name='add-from-public'),
    path('public/like/', views.item_like_toggle, name='item-like-toggle'),

    # comment
    path('comment/create/', views.comment_create, name='comment-create'),
    path('comment/delete/', views.comment_delete, name='comment-delete'),

]

app/items/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import ItemForm
from .models import Item

__all__ = (
    'item_list',
    'my_item_list',
    'item_add',
)


def item_list(request):
    items = Item.objects.filter(public_visibility=True)
    context = {
        'items': items,
    }
    return render(request, 'index.html', context)


@login_required
def my_item_list(request):
    if not request.user.is_authenticated:
        return redirect('members:login')

    my_items = Item.objects.filter(user=request.user)
    context = {
        'my_items': my_items,
    }
    return render(request, 'items/my_items_list.html', context)


@login_required
def item_add(request):
    if not request.user.is_authenticated:
        return redirect('members:login')

    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            item.save()
            return redirect('items:my-item-list')
    else:
        form = ItemForm()
    context = {
        'form': form,
    }
    return render(request, 'items/item_add.html', context)

app/items/views/__init__.py
from .add import *
from .list import *
from .detail import *
from .edit import *
from .item_like import *
from .delete import *
from .add_from_public import *
from .comment import *
from .purchase_complete import *
from .url_search import *

app/items/views/add.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from ..forms import ItemForm
from ..models import Item

__all__ = (
    'item_add',
)


@login_required(login_url='/login/')
def item_add(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            url = request.POST['purchase_url']
            Item.objects.add_from_search(request, url)
            return redirect('items:my-item-list')
    else:
        form = ItemForm()

    context = {
        'form': form,
    }

    return render(request, 'items/my_item/item_search.html', context)

app/items/views/add_from_public.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from ..models import Item

__all__ = (
    'add_from_public',
)


@login_required(login_url='/login/')
@require_POST
def add_from_public(request):
    item_pk = request.POST.get('pk', None)
    Item.objects.add_from_public(item_pk, request)
    message = '내 아이템에 추가되었습니다'
    context = {
        'message': message,
    }
    return HttpResponse(json.dumps(context), content_type='application/json')

app/items/views/comment.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST

from ..forms import CommentForm
from ..models import Item, ItemComment

__all__ = (
    'comment_create',
    'comment_delete',
)


@require_POST
def comment_create(request):
    item_pk = request.POST.get('pk', None)
    next_path = request.POST.get('next_path', None)
    parent_pk = request.POST.get('parent_pk', None)
    item = get_object_or_404(Item, pk=item_pk)
    try:
        parent = get_object_or_404(ItemComment, pk=parent_pk)
    except Exception:
        parent = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.item = item
        comment.parent = parent
        comment.save()
        context = {
            'comment': comment,
        }
        return render(request, 'items/comment/new_comment.html', context)
    return redirect(next_path)


@login_required(login_url='/login/')
@require_POST
def comment_delete(request):
    comment_pk = request.POST.get('pk', None)
    comment = get_object_or_404(ItemComment, pk=comment_pk)

    if comment.user == request.user:
        comment.delete()
        status = 1
        message = '삭제완료'
    else:
        status = 0
        message = '잘못된 접근입니다'

    context = {
        'status': status,
        'message': message,
    }

    return HttpResponse(json.dumps(context), content_type='application/json')

app/items/views/delete.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from ..models import Item

__all__ = (
    'item_delete',
)


@login_required(login_url='/login/')
@require_POST
def item_delete(request):
    item_pk = request.POST.get('pk', None)
    item = get_object_or_404(Item, pk=item_pk)
    if item.user == request.user:
        item.delete()
        message = '아이템이 삭제되었습니다'
        context = {
            'message': message,
        }
        return HttpResponse(json.dumps(context), content_type='application/json')

app/items/views/detail.py
from django.shortcuts import get_object_or_404, render

from ..forms import CommentForm
from ..models import Item

__all__ = (
    'item_detail',
    'public_item_detail',
    'purchase_item_detail',
)


def item_detail(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)
    comment_form = CommentForm()
    context = {
        'item': item,
        'comment_form': comment_form,
    }
    return render(request, 'items/my_item/item_detail.html', context)


def public_item_detail(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)
    comment_form = CommentForm()
    context = {
        'item': item,
        'comment_form': comment_form,
    }
    return render(request, 'items/public_item/public_item_detail.html', context)


def purchase_item_detail(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)
    comment_form = CommentForm()
    context = {
        'item': item,
        'comment_form': comment_form,
    }
    return render(request, 'items/my_item/purchase_item_detail.html', context)

app/items/views/edit.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render

from ..forms import ItemForm
from ..models import Item


@login_required(login_url='/login/')
def item_edit(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)
    if request.user != item.user:
        raise PermissionDenied('권한이 없습니다')

    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('items:my-item-list')
    else:
        form = ItemForm(instance=item)
    context = {
        'form': form,
    }
    return render(request, 'items/my_item/item_edit.html', context)

app/items/views/item_like.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from ..models import Item

__all__ = (
    'item_like_toggle',
)


@login_required(login_url='/login/')
@require_POST
def item_like_toggle(request):
    item_pk = request.POST.get('pk', None)
    item = get_object_or_404(Item, pk=item_pk)
    item_like, item_like_created = item.like_user_info_list.get_or_create(user=request.user)

    if not item_like_created:
        item_like.delete()
        message = '좋아요 취소'
    else:
        message = '좋아요'

    like_count = item.like_users.count()
    if like_count > 1:
        like_count_text = f'{like_count} likes'
    else:
        like_count_text = f'{like_count} like'
    context = {
        'like_count_text': like_count_text,
        'message': message,
    }

    return HttpResponse(json.dumps(context), content_type='application/json')

app/items/views/list.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render

from ..filter import ItemFilter
from ..forms import CommentForm
from ..models import Item

__all__ = (
    'item_list',
    'my_item_list',
    'my_complete_item_list',
)


def item_list(request):
    items = Item.objects.filter(public_visibility=True).annotate(num_like_users=Count('like_users'))\
        .order_by('-num_like_users', '-created_time')
    comment_form = CommentForm()
    item_filter = ItemFilter(request.GET, queryset=items)
    context = {
        'items': items,
        'comment_form': comment_form,
        'filter': item_filter,
    }
    return render(request, 'index.html', context)


@login_required(login_url='/login/')
def my_item_list(request):
    my_items = Item.objects.filter(user=request.user, is_purchase=False)
    total_cost = 0
    for my_item in my_items:
        total_cost += my_item.price

    context = {
        'my_items': my_items,
        'total_cost': total_cost,
    }
    return render(request, 'items/my_item/my_items_list.html', context)


@login_required(login_url='/login/')
def my_complete_item_list(request):
    my_items = Item.objects.filter(user=request.user, is_purchase=True).order_by('-modified_time')
    total_cost = 0
    for my_item in my_items:
        total_cost += my_item.price

    context = {
        'my_items': my_items,
        'total_cost': total_cost,
    }
    return render(request, 'items/my_item/my_complete_items_list.html', context)

app/items/views/purchase_complete.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from ..models import Item

__all__ = (
    'purchase_complete',
)


@login_required(login_url='/login/')
@require_POST
def purchase_complete(request):
    item_pk = request.POST.get('pk', None)
    Item.objects.purchase_complete(item_pk)
    message = '지르시느라 고생 많으셨습니다'
    context = {
        'message': message,
    }
    return HttpResponse(json.dumps(context), content_type='application/json')

app/items/views/url_search.py
from django.shortcuts import render

from utils.check_url_from_url_parser import CheckURL
from ..forms import ItemForm
from ..models.item import Item

__all__ = (
    'search_url',
)


def search_url(request):
    url = request.GET.get('url')
    context = {}

    if url:
        search_result = CheckURL(url)
        search_result.check_url_from_parser()

        item_img = search_result.item_data.item_img
        item_price = search_result.item_data.item_price
        item_name = search_result.item_data.item_name
        url = search_result.item_data.url
        form = ItemForm()

        context = {
            'form': form,
            'category_choices': Item.CHOICES_CATEGORY,
            'item_img': item_img,
            'item_price': item_price,
            'item_name': item_name,
            'url': url,
        }
    return render(request, 'items/my_item/item_search.html', context)

app/templates/items/my_item/item_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% block content %}

{% if request.user != item.user %}
 <meta http-equiv="REFRESH" content="0;url={% url 'items:public-item-detail' item_pk=item.pk %}">
{% endif %}
<div class="container body-container">


  <div class="item-detail-container">
    <div class="row align-items-center item-name-container">
      <h2 class="col-sm-12 text-center item-name">{{ item.name }}</h2>
      <div class="item-edit-delete-btn float-right">
        {% if request.user == item.user %}
          <a href="{% url 'items:item-edit' item_pk=item.pk %}" class="btn btn-primary btn-sm">수정</a>
          <button id="deleteBtn" class="btn btn-danger btn-sm" name="{{ item.pk }}">삭제</button>
        {% endif %}
      </div>
    </div>

    <div class="row justify-content-around align-items-center item-content-container">
      <div class="col-sm-6 order-sm-1">
        <div class="mb3">
          <img class="col-12 rounded detail-img mx-auto d-block"
          src="{% if item.img %}{{ item.img.url }}{% else %}{% static 'images/default_img.jpg' %}{% endif %}"
          alt="item-image">
        </div>
      </div>
      <div class="col-sm-4 order-sm-2">
        <div class="item-detail">
          <h3>상품 카테고리</h3>
          <span class="text-muted">{% if item.category %}{{ item.get_category_display }}{% else %} {% endif %}</span>
        </div>
        <div class="item-detail">
          <h3>상품 가격</h3>
          <span class="text-muted">{{ item.price|intcomma }}원</span>
        </div>
        <div class="item-detail">
          <h3>구입 링크</h3>
          <a href="{{ item.purchase_url }}" class="text-muted" target="_blank">
            {% if item.purchase_url %}
            {{ item.purchase_url|truncatechars:70 }}
            {% else %} {% endif %}
          </a>
        </div>
        <div class="item-detail">
          <h3>못 지른지</h3>
          <span class="text-muted">{{ item.created_time|timesince }}째</span>
        </div>
      </div>
    </div>
  </div>

  <div class="comment-container">
    {% include 'items/comment/comment-form.html' %}
  </div>


</div>

<script src="{% static 'js/comment.js' %}"></script>
<script type="text/javascript">
  var isAuth = "{{ request.user.is_authenticated }}";
  var csrfToken = "{{ csrf_token }}";


  $(document).on("click", ".comment-add-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'items:comment-create' %}";
    var nextPath = "/items/public/"+pk;
    commentAdd(pk, isAuth, url, csrfToken, nextPath);
  })

  $(document).on("click", ".comment-delete-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'items:comment-delete' %}";
    var count = "#itemCount";
    commentDel(pk, url, csrfToken, count);
  })

  $(document).on("click", ".reply-add-btn", function () {
    var pk = $(this).attr('name');
    replyAddForm(pk);
  })

  $(document).on("click", ".comment-reply-add-btn", function () {
    var parentPk = $(this).attr('name');
    var pk = {{ item.pk }};
    var url = "{% url 'items:comment-create' %}";
    var nextPath = "/items/public/"+pk;
    replyAdd(parentPk, pk, isAuth, url, csrfToken, nextPath);
  })

  $(document).on("click", ".reply-delete-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'items:comment-delete' %}";
    var count = "#itemCount";
    replyDel(pk, url, csrfToken, count);
  })

  $(document).on("click", "#deleteBtn", function() {
    var pk = $(this).attr('name');
    $.ajax({
      type: "POST",
      url: "{% url 'items:item-delete' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",

      success: function(response) {
        alert(response.message)
        window.location.replace("/items/list/")
      },
      error: function(request, status, error) {
        alert("로그인이 필요합니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })
</script>



{% endblock %}

app/templates/items/my_item/item_edit.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div class="container">
  <div class="item-edit-container">
    <form action="" method="POST" class="clearfix" enctype='multipart/form-data'>
      {% csrf_token %}
          {% for field in form %}
            <div class="form-group clearfix">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"form-control" }}
              {% for error in field.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endfor %}
      <div>
        <button type="submit" class="btn btn-dark">수정</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/items/my_item/my_items_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}


<div class="top-container container">
  <h3>내 지르미들</h3>
  <div class="right-top-container">
    <span class="text_muted">지름에 필요한 총 금액: {{ total_cost|intcomma }}원</span>
    <a href="{% url 'items:search-url' %}" class="btn btn-dark">Add item</a>
  </div>
</div>

<div class="album py-5 bg-light">
  <div class="container body-container">
    <div class="row">
      {% if not my_items %}
        <div class="empty-item">
          <p class="text-muted text-center">아이템이 없습니다</p>
        </div>
      {% endif %}

      {% for item in my_items %}
        <div class="custom-card-col">
          <div class="card mb-4 box-shadow align-items-center">
            <a href="{% url 'items:item-detail' item_pk=item.pk %}">
              <div class="card-button align-items-center">
                <img class="card-img-top"
                src="{% if item.img %}{{ item.img.url }}{% else %}{% static 'images/default_img.jpg' %}{% endif %}"
                alt="item-image">
                <span class="price-text">{{ item.price|intcomma }} 원</span>
                <p class="card-text text-center">{{ item.name }}</p>
              </div>
            </a>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button id="completeBtn" class="btn btn-sm btn-primary"
                  name="{{ item.pk }}">지름 완료</button>
                  <button id="deleteBtn" class="btn btn-sm btn-danger"
                  name="{{ item.pk }}">삭제</button>
                </div>
                <small class="text-muted">못 지른지 {{ item.created_time|timesince }}째</small>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on("click", "#completeBtn", function() {
    var pk = $(this).attr('name')
    $.ajax({
      type: "POST",
      url: "{% url 'items:purchase-complete' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",

      success: function(response) {
        alert(response.message)
        window.location.replace("/items/list/")
      },
      error: function(request, status, error) {
        alert("로그인이 필요합니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })

  $(document).on("click", "#deleteBtn", function() {
    var pk = $(this).attr('name')
    $.ajax({
      type: "POST",
      url: "{% url 'items:item-delete' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",

      success: function(response) {
        alert(response.message)
        window.location.replace("/items/list/")
      },
      error: function(request, status, error) {
        alert("로그인이 필요합니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })
</script>





{% endblock %}

app/templates/items/my_item/purchase_item_detail.html
{% extends 'base.html' %}
{% load static %}
{% load id_from_email_tag %}
{% load humanize %}
{% block content %}

<div class="container body-container">
  <div class="item-detail-container">
    <div class="row align-items-center item-name-container">
      <h2 class="col-lg-12 text-center item-name">{{ item.name }}</h2>
    </div>
    <div class="row justify-content-around align-items-center item-content-container">
      <div class="col-lg-6 order-lg-1">
        <div class="mb3">
          <img class="col-12 rounded detail-img"
          src="{% if item.img %}{{ item.img.url }}{% else %}{% static 'images/default_img.jpg' %}{% endif %}"
          alt="item-image">
        </div>
      </div>
      <div class="col-lg-4 order-lg-2">
        <div class="item-detail">
          <h3>상품 카테고리</h3>
          <span class="text-muted">
            {% if item.category %}
            {{ item.get_category_display }}
            {% else %} {% endif %}</span>
        </div>
        <div class="item-detail">
          <h3>상품 가격</h3>
          <span class="text-muted">{{ item.price|intcomma }}원</span>
        </div>
        <div class="item-detail">
          <h3>구입 링크</h3>
          <a href="{{ item.purchase_url }}" class="text-muted" target="_blank">
            {% if item.purchase_url %}
            {{ item.purchase_url|truncatechars:70 }}
            {% else %} {% endif %}
          </a>
        </div>
        <div class="item-detail">
          <h3>구매 날짜</h3>
          <span class="text-muted">{{ item.purchase_date|date:'y년 n월 j일' }}</span>
        </div>
      </div>
    </div>
  </div>

  <div class="comment-container">
    {% include 'items/comment/comment-form.html' %}
  </div>
</div>

<script type="text/javascript">
  $(document).on("click", ".comment-add-btn", function () {
    var pk = $(this).attr('name');
    var content = $("#addComment-"+pk+">textarea").val();
    var nextPath = "/items/list/complete/"+pk;
    var isAuth = "{{ request.user.is_authenticated }}";
    if (content && isAuth == "True") {
      $.ajax({
        type: "POST",
        url: "{% url 'items:comment-create' %}",
        data: {
          'pk': pk,
          'content': content,
          'next_path': nextPath,
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        dataType: "html",

        success: function(data, textStatus, jqXHR) {
          $("#addComment-"+pk+">textarea").val("");
          $("#commentList-"+pk).append(data);
          $("#itemCount").load(window.location + " #itemCount");
        },
        error: function(request, status, error) {
          alert("잘못된 접근입니다");
          console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        }
      });
    } else if (content && isAuth == "False") {
      alert("로그인이 필요합니다");
      window.location.replace("/login_view/?next="+nextPath);
    } else {
      alert("댓글 내용을 입력해주세요")
    }
  })

  $(document).on("click", ".comment-delete-btn", function () {
    var pk = $(this).attr('name');
    $.ajax({
      type: "POST",
      url: "{% url 'items:comment-delete' %}",
      data: {
        'pk': pk,
        'csrfmiddlewaretoken': '{{ csrf_token }}'
      },
      dataType: "json",

      success: function(response) {
        if(response.status){
          $("#comment-"+pk).remove();
          $("#itemCount").load(window.location + " #itemCount");
        }
      },
      error: function(request, status, error) {
        alert("잘못된 접근입니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })

</script>



{% endblock %}