app/members/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    GENERATION_10S = '1'
    GENERATION_20S = '2'
    GENERATION_30S = '3'
    GENERATION_40S = '4'
    GENERATION_50S_OR_MORE = '5'
    CHOICES_GENERATION = (
        (GENERATION_10S, '10대'),
        (GENERATION_20S, '20대'),
        (GENERATION_30S, '30대'),
        (GENERATION_40S, '40대'),
        (GENERATION_50S_OR_MORE, '50대 이상'),
    )
    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'
    CHOICES_GENDER = (
        (GENDER_MALE, '남성'),
        (GENDER_FEMALE, '여성'),
    )

    username = models.CharField(max_length=50, unique=False, blank=True, null=True)
    email = models.EmailField('이메일', max_length=50, unique=True, null=True)
    generation = models.CharField('세대', max_length=10, choices=CHOICES_GENERATION, null=True)
    gender = models.CharField('성별', max_length=10, choices=CHOICES_GENDER, null=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyUserManager()

    def toggle_like_item(self, item):
        like, like_created = self.like_item_info_list.get_or_create(item=item)
        if not like_created:
            like.delete()
        return like_created

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    class Meta:
        verbose_name = '사용자'
        verbose_name_plural = f'{verbose_name} 목록'

app/members/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

User = get_user_model()

__all__ = (
    'SignUpForm',
)


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.pop('autofocus', None)

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
            'generation',
            'gender',
            'username',
        )

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise ValidationError('이미 사용중인 이메일입니다')
        return data

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise ValidationError('비밀번호와 비밀번호 확인란이 같지 않습니다')
        return password2

    def signup(self, request, user):
        user.gender = self.cleaned_data['gender']
        user.generation = self.cleaned_data['generation']
        user.save()

app/members/apis/__init__.py
from .facebook_login import *
from .user import *

app/members/urls/views.py
from django.urls import path

from .. import views

app_name = 'members'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # facebook
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('facebook-signup/', views.facebook_signup, name='facebook-signup'),
]

app/members/views/__init__.py
from .facebook_login import *
from .facebook_signup import *
from .login import *
from .logout import *
from .signup import *

app/members/views/facebook_login.py
import requests
from django.conf import settings
from django.contrib.auth import login, get_user_model
from django.shortcuts import redirect, render

from members.forms import SignUpForm

User = get_user_model()

__all__ = (
    'facebook_login',
)


def facebook_login(request):
    client_app_id = settings.FACEBOOK_APP_ID
    client_secret = settings.FACEBOOK_SECRET_CODE
    url_access_token = 'https://graph.facebook.com/v2.12/oauth/access_token'
    url_me = 'https://graph.facebook.com/v2.12/me'
    code = request.GET['code']

    redirect_uri = 'https://zirmi.net/facebook-login/'
    params_access_token = {
        'client_id': client_app_id,
        'redirect_uri': redirect_uri,
        'client_secret': client_secret,
        'code': code,
    }
    response = requests.get(url_access_token, params_access_token)
    response_dict = response.json()

    params = {
        'access_token': response_dict['access_token'],
        'fields': ','.join([
            'id',
            'name',
            'email',
            'age_range',
            'gender',
        ])
    }
    response = requests.get(url_me, params)
    response_dict = response.json()

    facebook_id = response_dict.get('id', None)
    facebook_email = response_dict.get('email', None)
    try:
        facebook_age_range = response_dict['age_range']['min']
    except KeyError:
        facebook_generation = ''
    else:
        if facebook_age_range < 12:
            facebook_generation = '1'
        elif facebook_age_range < 22:
            facebook_generation = '2'
        elif facebook_age_range < 32:
            facebook_generation = '3'
        elif facebook_age_range < 42:
            facebook_generation = '4'
        else:
            facebook_generation = '5'
    try:
        facebook_gender = response_dict['gender']
    except KeyError:
        facebook_gender = ''
    else:
        if facebook_gender == 'male':
            facebook_gender = 'm'
        elif facebook_gender == 'femal':
            facebook_gender = 'f'
    try:
        user = User.objects.get(email=facebook_email)
    except User.DoesNotExist:
        form = SignUpForm()
        context = {
            'signup_form': form,
            'facebook_id': facebook_id,
            'facebook_email': facebook_email,
            'facebook_generation': facebook_generation,
            'facebook_gender': facebook_gender,
        }
        return render(request, 'members/facebook_signup.html', context)
    else:
        login(request, user, backend='members.backends.FacebookBackend')
        return redirect('index')

app/members/views/facebook_signup.py
from django.contrib.auth import authenticate, login, get_user_model
from django.shortcuts import redirect, render

from ..forms import SignUpForm

User = get_user_model()

__all__ = (
    'facebook_signup',
)


def facebook_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            generation = form.cleaned_data['generation']
            gender = form.cleaned_data['gender']
            User.objects.create_user(
                username=username,
                email=email,
                password=password,
                generation=generation,
                gender=gender,
            )
            new_user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect('index')
        else:
            form = SignUpForm()
        context = {
            'signup_form': form,
        }
        return render(request, 'members/facebook_signup.html', context)

app/members/views/login.py
from django.contrib.auth import authenticate, login, get_user_model
from django.shortcuts import redirect, render

User = get_user_model()

__all__ = (
    'login_view',
)


def login_view(request):
    # next url 가져옴
    next_url = request.GET.get('next')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if not user:
            if User.objects.filter(email=email):
                context = {
                    'error': '비밀번호가 틀렸습니다',
                }
            else:
                context = {
                    'error': '없는 이메일입니다. 회원가입 해주세요',
                }
            return render(request, 'members/login.html', context)
        else:
            login(request, user)
            # next url 있을 경우 next url로 redirect 설정
            if next_url:
                return redirect(next_url)
            return redirect('index')
    return render(request, 'members/login.html')

app/members/views/login_view.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render

__all__ = (
    'login_view',
)


def login_view(request):
    # next url 가져옴
    next_url = request.GET.get('next')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            # next url 있을 경우 next url로 redirect 설정
            if next_url:
                return redirect(next_url)
            return redirect('index')
    return render(request, 'members/login.html')

app/members/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import redirect

__all__ = (
    'logout_view',
)


def logout_view(request):
    logout(request)
    return redirect('index')

app/members/views/logout_view.py
from django.contrib.auth import logout
from django.shortcuts import redirect

__all__ = (
    'logout_view',
)


def logout_view(request):
    logout(request)
    return redirect('index')

app/members/views/signup.py
from django.contrib.auth import authenticate, get_user_model, login
from django.shortcuts import redirect, render

from ..forms import SignUpForm

User = get_user_model()

__all__ = (
    'signup_view',
)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect('index')
    else:
        form = SignUpForm()
    context = {
        'signup_form': form,
    }
    return render(request, 'members/signup.html', context)

app/members/views/signup_view.py
from django.contrib.auth import authenticate, get_user_model, login
from django.shortcuts import redirect, render

from ..forms import SignUpForm

User = get_user_model()

__all__ = (
    'signup_view',
)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect('index')
    else:
        form = SignUpForm()
    context = {
        'signup_form': form,
    }
    return render(request, 'members/signup.html', context)

app/templates/members/facebook_signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
	<div class="signup_view-container">
		<h4>페이스북으로 회원가입</h4><br>
		<form action="{% url 'members:facebook-signup' %}" method="POST" class="clearfix">
			{% csrf_token %}
      {% for field in signup_form %}
				{% if not field.label == 'Username' %}
		      <div class="form-group clearfix">
		        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
		        {% if field.label == '이메일' %}
							{% with ev=facebook_email %}
			          {% if ev %}
									{% render_field signup_form.email class="form-control" placeholder="이메일을 적어주세요" readonly="" value=ev %}
			          {% else %}
			            {{ field|add_class:"form-control"|attr:"autofocus" }}
			          {% endif %}
							{% endwith %}

						{% elif field.label == '비밀번호' %}
		          {{ field|add_class:"form-control"|attr:"autofocus" }}

						{% elif field.label == '세대' %}
							<select name="generation" id="id_generation" class="form-control">
								 {% for x in signup_form.fields.generation.choices %}
								 <option value="{{ x.0 }}" {% if x.0 == facebook_generation %}selected{% endif %}>
									 {{ x.1 }}
								 </option>
								 {% endfor %}
							 </select>

						{% elif field.label == '성별' %}
							<select name="gender" id="id_gender" class="form-control">
								 {% for x in signup_form.fields.gender.choices %}
								 <option value="{{ x.0 }}" {% if x.0 == facebook_gender %}selected{% endif %}>
									 {{ x.1 }}
								 </option>
								 {% endfor %}
							 </select>

						 {% else %}
						 	{{ field|add_class:"form-control" }}

		        {% endif %}
		        {% for error in field.errors %}
		          <p>{{ error }}</p>
		        {% endfor %}
		      </div>
				{% endif %}
    	{% endfor %}
			<input type="text" name="username" value="{{ facebook_id }}" hidden>
	    {% if redirect_field_value %}
	      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
	    {% endif %}
			<div>
				<button type="submit" class="btn btn-dark">회원 가입</button>
			</div>
		</form>
	</div>
</div>



{% endblock %}

app/templates/members/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container member-container">
  <div class="login-container">
    <form class="form-signin align-items-center" action="" method="POST">
      {% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">로그인 해주세요</h1>
      <div class="form-group">
        <input class="form-control" type="text" name="email" placeholder="Email address" required autofocus>
      </div>
      <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password" required>
      </div>

      <button type="submit" class="btn btn-lg btn-dark btn-block">로그인</button>
      <a href="https://www.facebook.com/v2.12/dialog/oauth?client_id=194729581179158&scope=email,public_profile&redirect_uri={{ request.scheme }}://{{ request.get_host }}/facebook-login/"
      class="btn btn-lg loginBtn loginBtn--facebook btn-block">페이스북 로그인</a>
      <p class="mt-3 mb-3 text-muted">아직 아이디가 없나요?</p>
      <a class="btn btn-lg btn-warning btn-block" href="{% url 'members:signup' %}">회원가입</a>
      <p class="mt-5 mb-3 text-muted">&copy; 지르미</p>
    </form>
  </div>
</div>


{% if error %}
  <script type="text/javascript">
    alert('{{ error }}');
  </script>
{% endif %}

{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block content %}
<div class="container member-container">
	<div class="signup_view-container">
		<h4>회원가입</h4><br>
		<form action="" method="POST" class="clearfix">
			{% csrf_token %}
        {% for field in signup_form %}
					{% if not field.label == 'Username' %}
	        	<div class="form-group clearfix">
							<label for="{{ field.id_for_label }}">{{ field.label }}</label>
							{% if field.label == '이메일' %}
								{{ field|add_class:'form-control'|attr:'autofocus' }}
							{% else %}
	            	{{ field|add_class:"form-control" }}
							{% endif %}
	            {% for error in field.errors %}
	            	<p>{{ error }}</p>
	            {% endfor %}
						</div>
					{% endif %}
        {% endfor %}
			<div>
				<button type="submit" class="btn btn-dark">회원 가입</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}