app/reviews/models.py
from django.contrib.auth import get_user_model
from django.db import models

from django_summernote import models as summer_model
from django_summernote import fields as summer_fields

from core.models import TimeStampedModel
from items.models import Item

User = get_user_model()


class SummerNote(summer_model.Attachment):
    summer_field = summer_fields.SummernoteTextField(default='')


class Review(TimeStampedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='user_reviews',
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.SET_NULL,
        null=True,
    )
    title = models.CharField('제목', max_length=200)
    content = models.TextField('내용', default='')
    view_count = models.IntegerField('조회수', default=0)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return f'{self.title} - {self.user}'


class ReviewCommentManager(models.Manager):
    def no_reply_all(self):
        queryset = self.filter(parent=None)
        return queryset


class ReviewComment(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    review = models.ForeignKey(Review, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField('')
    parent = models.ForeignKey('self', blank=True, null=True, related_name='replies', on_delete=models.CASCADE)

    objects = ReviewCommentManager()

    class Meta:
        ordering = ['created_time']

    def children(self):
        return ReviewComment.objects.filter(parent=self)

    def __str__(self):
        return f'{self.pk}. {self.content} - {self.user}'

app/reviews/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import Review, ReviewComment


class ReviewForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # user가 구매완료한 제품만 표시
        self.fields['item'].queryset = self.fields['item'].queryset.filter(user=request.user, is_purchase=True)
        self.fields['item'].label = '제품명'
        self.fields['item'].label_from_instance = self.label_from_instance

        class_update_fields = ('item', 'title')
        for field in class_update_fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })

    @staticmethod
    def label_from_instance(self):
        return f'{self.name}'

    class Meta:
        model = Review
        fields = (
            'item',
            'title',
            'content',
        )
        widgets = {
            'content': SummernoteWidget(),
        }


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': "댓글을 입력해주세요",
                }
            )
        }

app/reviews/apis/__init__.py
from .review import *
from .comment import *

app/reviews/urls/views.py
from django.urls import path

from .. import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name='review-list'),
    path('add/', views.review_add, name='review-add'),
    path('delete/', views.review_delete, name='review-delete'),
    path('search/', views.search_review, name='search-review'),
    path('<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/edit/', views.review_edit, name='review-edit'),

    # comment
    path('comment/create/', views.comment_create, name='comment-create'),
    path('comment/delete/', views.comment_delete, name='comment-delete'),

]

app/reviews/views/__init__.py
from .add import *
from .comment import *
from .delete import *
from .detail import *
from .edit import *
from .list import *
from .search import *

app/reviews/views/add.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from ..forms import ReviewForm

__all__ = (
    'review_add',
)


@login_required(login_url='/login/')
def review_add(request):
    if request.method == 'POST':
        form = ReviewForm(request, request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:review-list')
    else:
        form = ReviewForm(request)
    context = {
        'form': form,
    }
    return render(request, 'reviews/review_add.html', context)

app/reviews/views/comment.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST

from ..forms import ReviewCommentForm
from ..models import ReviewComment, Review

__all__ = (
    'comment_create',
    'comment_delete',
)


@login_required(login_url='/login/')
@require_POST
def comment_create(request):
    review_pk = request.POST.get('pk', None)
    next_path = request.POST.get('next_path', None)
    parent_pk = request.POST.get('parent_pk', None)
    review = get_object_or_404(Review, pk=review_pk)
    try:
        parent = get_object_or_404(ReviewComment, pk=parent_pk)
    except Exception:
        parent = None
    form = ReviewCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.parent = parent
        comment.save()
        context = {
            'comment': comment,
        }
        return render(request, 'items/comment/new_comment.html', context)
    return redirect(next_path)


@login_required(login_url='/login/')
@require_POST
def comment_delete(request):
    comment_pk = request.POST.get('pk', None)
    comment = get_object_or_404(ReviewComment, pk=comment_pk)

    if comment.user == request.user:
        comment.delete()
        status = 1
        message = '삭제완료'
    else:
        status = 0
        message = '잘못된 접근입니다'

    context = {
        'status': status,
        'message': message,
    }

    return HttpResponse(json.dumps(context), content_type='application/json')

app/reviews/views/delete.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from ..models import Review

__all__ = (
    'review_delete',
)


@login_required(login_url='/login/')
@require_POST
def review_delete(request):
    review_pk = request.POST.get('pk', None)
    review = get_object_or_404(Review, pk=review_pk)
    if review.user == request.user:
        review.delete()
        message = '리뷰가 삭제되었습니다'
        context = {
            'message': message,
        }
        return HttpResponse(json.dumps(context), content_type='application/json')

app/reviews/views/detail.py
from django.db.models import F
from django.shortcuts import render

from ..forms import ReviewCommentForm
from ..models import Review

__all__ = (
    'review_detail',
)


def review_detail(request, review_pk):
    # view 수 증가
    view = Review.objects.filter(pk=review_pk)
    view.update(view_count=F('view_count') + 1)

    comment_form = ReviewCommentForm()
    review = Review.objects.get(pk=review_pk)
    context = {
        'review': review,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/review_detail.html', context)

app/reviews/views/edit.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render

from ..forms import ReviewForm
from ..models import Review


@login_required(login_url='/login/')
def review_edit(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user != review.user:
        raise PermissionDenied('권한이 없습니다')

    if request.method == 'POST':
        form = ReviewForm(request, request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()
            return redirect('reviews:review-list')
    else:
        form = ReviewForm(request, instance=review)
    context = {
        'form': form,
    }
    return render(request, 'reviews/review_edit.html', context)

app/reviews/views/list.py
from datetime import datetime

from django.core.paginator import Paginator
from django.shortcuts import render

from ..models import Review

__all__ = (
    'review_list',
)


def review_list(request):
    reviews_list = Review.objects.all()
    paginator = Paginator(reviews_list, 30)
    paginator_num = range(1, paginator.num_pages + 1)
    page = request.GET.get('page')
    reviews = paginator.get_page(page)
    today_date = datetime.now().strftime('%Y. %-m. %d')

    context = {
        'today_date': today_date,
        'reviews': reviews,
        'paginator_num': paginator_num,
    }
    return render(request, 'reviews/review_list.html', context)

app/reviews/views/search.py
from datetime import datetime

from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render

from reviews.models import Review


def search_review(request):
    search_text = request.GET.get('search-text')
    search_type = request.GET.get('search-type')

    # search 후 다음 페이지 넘겨도 search 정보 유지
    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    if search_text:
        if search_type == 'title':
            reviews_list = Review.objects.filter(title__contains=search_text)
        elif search_type == 'content':
            reviews_list = Review.objects.filter(content__contains=search_text)
        elif search_type == 'item':
            reviews_list = Review.objects.filter(item__name__contains=search_text)
        else:
            reviews_list = Review.objects.filter(
                Q(title__contains=search_text) | Q(content__contains=search_text) | Q(item__name__contains=search_text)
            )
        paginator = Paginator(reviews_list, 30)
        paginator_num = range(1, paginator.num_pages + 1)
        page = request.GET.get('page')
        reviews = paginator.get_page(page)

    else:
        reviews_list = Review.objects.all()
        paginator = Paginator(reviews_list, 30)
        paginator_num = range(1, paginator.num_pages + 1)
        page = request.GET.get('page')
        reviews = paginator.get_page(page)

    today_date = datetime.now().strftime('%Y. %-m. %d')

    context = {
        'today_date': today_date,
        'reviews': reviews,
        'search_text': search_text,
        'paginator_num': paginator_num,
        'parameters': parameters,
    }

    return render(request, 'reviews/review_list.html', context)

app/templates/reviews/post_review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <form method="post" action="">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}"
          class="font-weight-bold col-lg-1 col-form-label">{{ field.label }}</label>
          <div class="col-lg-11">
            {{ field|safe }}
          </div>
        </div>
      {% endfor %}
      <div class="post-review-btn">
        <button type="submit" class="btn btn-dark btn-lg btn-block">등록</button>
      </div>
  </form>
</div>



{% endblock %}

app/templates/reviews/review_add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container review-add-container">
  <form method="post" action="">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}"
          class="font-weight-bold col-lg-1 col-form-label">{{ field.label }}</label>
          <div class="col-lg-11">
            {{ field|safe }}
          </div>
        </div>
      {% endfor %}
      <div class="post-review-btn">
        <button type="submit" class="btn btn-dark btn-lg btn-block">등록</button>
      </div>
  </form>
</div>



{% endblock %}

app/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load id_from_email_tag %}

{% block content %}

<div class="container">
  <div class="review-item-name-container">
    <span class="review-item-name">{{ review.item.name }}</span>
  </div>
  <div class="review-title-container">
    <span class="review-title">{{ review.title }}</span>
  </div>
  <div class="review-info-container clearfix">
    <span class="review-date-view-count">{{ review.created_time|date:'Y. n. j G:i' }} | 조회수 {{ review.view_count|intcomma }}</span>
    <div class="edit-delete-btn">
      <a href="{% url 'reviews:review-list' %}" class="btn btn-sm btn-dark">목록</a>
      {% if request.user == review.user %}
      <a href="{% url 'reviews:review-edit' review_pk=review.pk %}" class="btn btn-sm btn-primary">수정</a>
      <button id="deleteBtn" class="btn btn-sm btn-danger" name="{{ review.pk }}">삭제</button>
      {% endif %}

    </div>
  </div>
  <hr>
  <div class="review-content-container">
    {{ review.content|safe }}
  </div>
  <br><br>
  <hr>
  <br>

  <div class="comment-container">
    {% include 'reviews/comment/comment-form.html' %}
  </div>

</div>

<script src="{% static 'js/comment.js' %}"></script>
<script type="text/javascript">
  var isAuth = "{{ request.user.is_authenticated }}";
  var csrfToken = "{{ csrf_token }}";

  $(document).on("click", ".comment-add-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'reviews:comment-create' %}";
    var nextPath = "/reviews/"+pk;
    commentAdd(pk, isAuth, url, csrfToken, nextPath);
  })

  $(document).on("click", ".comment-delete-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'reviews:comment-delete' %}";
    var count = "#reviewCount";
    commentDel(pk, url, csrfToken, count);
  })

  $(document).on("click", ".reply-add-btn", function () {
    var pk = $(this).attr('name');
    replyAddForm(pk);
  })

  $(document).on("click", ".comment-reply-add-btn", function () {
    var parentPk = $(this).attr('name');
    var pk = {{ review.pk }};
    var url = "{% url 'reviews:comment-create' %}";
    var nextPath = "/reviews/"+pk;
    replyAdd(parentPk, pk, isAuth, url, csrfToken, nextPath);
  })

  $(document).on("click", ".reply-delete-btn", function () {
    var pk = $(this).attr('name');
    var url = "{% url 'reviews:comment-delete' %}";
    var count = "#reviewCount";
    replyDel(pk, url, csrfToken, count);
  })

  $(document).on("click", "#deleteBtn", function() {
    var pk = $(this).attr('name');
    $.ajax({
      type: "POST",
      url: "{% url 'reviews:review-delete' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",

      success: function(response) {
        alert(response.message)
        window.location.replace("/reviews/")
      },
      error: function(request, status, error) {
        alert("로그인이 필요합니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })

</script>


{% endblock %}

app/templates/reviews/review_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <form method="post" action="">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}"
          class="font-weight-bold col-lg-1 col-form-label">{{ field.label }}</label>
          <div class="col-lg-11">
            {{ field|safe }}
          </div>
        </div>
      {% endfor %}
      <div class="post-review-btn">
        <button type="submit" class="btn btn-dark btn-lg btn-block">수정</button>
      </div>
  </form>
</div>



{% endblock %}

app/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load id_from_email_tag %}
{% load date_formatter_tag %}

{% block content %}

<div class="board-container">
  <div class="container">
    <div class="top-container container">
      <a href="/reviews/"><h3>지르미들 후기</h3></a>
      <div class="add-review-container clearfix">
        <a href="{% url 'reviews:review-add' %}" class="review-add-btn btn btn-dark btn-fab" id="main">
          <i class="material-icons">
            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
              <path fill="#a7a7a7" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" />
            </svg>
          </i>
        </a>
      </div>
    </div>
    <div id="table">
      <div class="table-header-row">
        <span class="table-cell col1">번호</span>
        <span class="table-cell col2">제목</span>
        <span class="table-cell col3">작성자</span>
        <span class="table-cell col4">날짜</span>
        <span class="table-cell col5">조회수</span>
      </div>
      {% if not reviews %}
        <div class="table-row">
          <span class="table-cell empty-review">리뷰가 없습니다</span>
        </div>
      {% else %}
        {% for review in reviews %}
        <div class="table-row">
          <span class="table-cell col1">{{ review.pk }}</span>
          <span class="table-cell col2">
            <a href="{% url 'reviews:review-detail' review_pk=review.pk %}">
              {{ review.title|linebreaksbr }} <span class="review-comments">[{{ review.comments.count }}]</span>
              {% if review.created_time|date:"Y. n. j" ==  today_date %}
              &emsp;<span class="badge badge-warning">New</span>
              {% endif %}
            </a>
          </span>
          <span class="table-cell col3">{{ review.user|id_from_email }}</span>
          <span class="table-cell col4">{{ review.created_time|date_formatter }}</span>
          <span class="table-cell col5">{{ review.view_count|intcomma }}</span>
        </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>


  <div id="small-table">
    {% if not reviews %}
      <div class="small-table-row">
        <span class="empty-review">리뷰가 없습니다</span>
      </div>
    {% else %}
      {% for review in reviews %}
        <a href="{% url 'reviews:review-detail' review_pk=review.pk %}">
          <div class="small-table-row no-gutters">
            <div class="small-table-detail">
              <div class="small-table-title">
                <span>
                  {{ review.title|linebreaksbr }}
                  {% if review.created_time|date:"Y. n. j" ==  today_date %}
                    &ensp;<span class="badge badge-warning">New</span>
                  {% endif %}
                </span>
              </div>
              <div class="small-table-review-info">
                <span>{{ review.user|id_from_email }}</span>
                <span class="review-date">{{ review.created_time|date_formatter }}</span>
                <span><i class="eye-icon fas fa-eye"></i> {{ review.view_count|intcomma }}</span>
              </div>
            </div>
            <div class="small-table-comments">
              <div class="comments-box">
                <span class="comments-count">{{ review.comments.count }}</span>
                <br>
                <span class="comments-text">댓글</span>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    {% endif %}
  </div>
  <nav>
    <ul class="pagination justify-content-center">
      {% if reviews.has_previous %}
        <li class="page-item">
          <a class="page-link"
          href="?page=1{% if parameters %}&{{ parameters }}{% endif %}">&laquo;</a>
        </li>
        <li class="page-item">
          <a class="page-link"
          href="?page={{ reviews.previous_page_number }}{% if parameters %}&{{ parameters }}{% endif %}">&lsaquo;</a>
        </li>
      {% endif %}
      {% for i in paginator_num %}
        <li class="page-item {% if i == reviews.number %}active{% endif %}">
          <a class="page-link" href="?page={{ i }}{% if parameters %}&{{ parameters }}{% endif %}">{{ i }}</a>
        </li>
      {% endfor %}
      {% if reviews.has_next %}
        <li class="page-item">
          <a class="page-link"
          href="?page={{ reviews.next_page_number }}{% if parameters %}&{{ parameters }}{% endif %}">&rsaquo;</a>
        </li>
        <li class="page-item">
          <a class="page-link"
          href="?page={{ reviews.paginator.num_pages }}{% if parameters %}&{{ parameters }}{% endif %}">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>

  <div class="search-review-container">
    <form action="{% url 'reviews:search-review' %}" method="get" class="review-search-form">
      <div class="input-group">
        <div class="input-group-prepend">
          <select class="custom-select" name="search-type">
            <option value="title">제목</option>
            <option value="content">내용</option>
            <option value="item">상품명</option>
            <option value="total">종합</option>
          </select>
        </div>
        <input type="text" name="search-text" class="form-control" value="{{ search_text }}">
        <div class="input-group-append">
          <button type="submit" class="form-control">검색</button>
        </div>
      </div>
    </form>
  </div>


</div>


{% endblock %}