app/items/models/item.py
from urllib.parse import urlparse

from django.contrib.auth import get_user_model
from django.core.files import File
from django.db import models

from core.models import TimeStampedModel
from utils.check_url_from_url_parser import CheckURL
from utils.file import download, get_buffer_ext
from ..models.managers import ItemManager

User = get_user_model()

__all__ = (
    'Item',
)


class Item(TimeStampedModel):
    CATEGORY_A = 'a'
    CATEGORY_B = 'b'
    CATEGORY_C = 'c'
    CATEGORY_D = 'd'
    CATEGORY_E = 'e'
    CATEGORY_F = 'f'
    CATEGORY_G = 'g'
    CATEGORY_H = 'h'
    CATEGORY_I = 'i'
    CATEGORY_J = 'j'
    CATEGORY_K = 'k'
    CHOICES_CATEGORY = (
        (CATEGORY_A, '패션의류/잡화'),
        (CATEGORY_B, '유아용품'),
        (CATEGORY_C, '뷰티'),
        (CATEGORY_D, '주방/생활용품'),
        (CATEGORY_E, '디지털/가전제품'),
        (CATEGORY_F, '가구/인테리어'),
        (CATEGORY_G, '운동용품'),
        (CATEGORY_H, '여행'),
        (CATEGORY_I, '도서/음반/공연'),
        (CATEGORY_J, '자동차용품'),
        (CATEGORY_K, '기타'),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='user_items'
    )
    name = models.CharField('상품명', max_length=50)
    purchase_url = models.URLField('상품 URL', max_length=400, blank=True)
    price = models.IntegerField('상품 가격')
    category = models.CharField('상품 카테고리', max_length=100, choices=CHOICES_CATEGORY, blank=False)
    img = models.ImageField('상품 이미지', upload_to='items', blank=True)
    public_visibility = models.BooleanField('공개 여부', default=True)
    is_purchase = models.BooleanField('구매 여부', default=False)
    purchase_date = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    like_users = models.ManyToManyField(
        User,
        through='ItemLike',
        related_name='like_items',
        blank=True
    )

    objects = ItemManager()

    class Meta:
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        if Item.objects.filter(pk=self.pk):
            super().save()
        else:
            if self.purchase_url and not self.img:
                url = self.purchase_url
                search_result = CheckURL(url)
                search_result.check_url_from_parser()

                item_img_url = search_result.item_data.item_img
                if item_img_url:
                    temp_file = download(item_img_url)
                    file_name = '{urlparse}.{ext}'.format(
                        urlparse=urlparse(item_img_url).path.split('/')[-1].split('.')[0],
                        ext=get_buffer_ext(temp_file)
                    )
                    self.purchase_url = search_result.item_data.url
                    self.img.save(file_name, File(temp_file))
            super().save()

    def __str__(self):
        return f'{self.pk}. {self.name} - {self.user}'

app/items/urls/views.py
from django.urls import path
from .. import views

app_name = 'items'
urlpatterns = [
    path('list/', views.my_item_list, name='my-item-list'),
    path('list/<int:item_pk>/', views.item_detail, name='item-detail'),
    path('list/<int:item_pk>/edit/', views.item_edit, name='item-edit'),
    path('delete/', views.item_delete, name='item-delete'),

    # search
    path('search/', views.search_url, name='search-url'),
    path('search/add/', views.item_add, name='item-add'),

    # complete
    path('complete/', views.purchase_complete, name='purchase-complete'),
    path('complete/list/', views.my_complete_item_list, name='my-complete-item-list'),
    path('complete/list/<int:item_pk>/', views.purchase_item_detail, name='purchase-item-detail'),

    # public
    path('public/<int:item_pk>/', views.public_item_detail, name='public-item-detail'),
    path('public/add/', views.add_from_public, name='add-from-public'),
    path('public/like/', views.item_like_toggle, name='item-like-toggle'),

    # comment
    path('comment/create/', views.comment_create, name='comment-create'),
    path('comment/delete/', views.comment_delete, name='comment-delete'),

]

app/members/urls/views.py
from django.urls import path

from .. import views

app_name = 'members'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # facebook
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('facebook-signup/', views.facebook_signup, name='facebook-signup'),
]

app/reviews/urls/views.py
from django.urls import path

from .. import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name='review-list'),
    path('add/', views.review_add, name='review-add'),
    path('delete/', views.review_delete, name='review-delete'),
    path('search/', views.search_review, name='search-review'),
    path('<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/edit/', views.review_edit, name='review-edit'),

    # comment
    path('comment/create/', views.comment_create, name='comment-create'),
    path('comment/delete/', views.comment_delete, name='comment-delete'),

]

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>지르미</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/signin.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="{% static 'css/header.css' %}">
	<link rel="stylesheet" href="{% static 'css/board.css' %}">
	<link rel="stylesheet" href="{% static 'css/footer.css' %}">
	<link rel="stylesheet" href="{% static 'css/page_404.css' %}">
	<link rel="icon" href="{% static 'favicon-128.png' %}" sizes="128x128">
</head>

<body>
	<div class="header-wrap">
		<header class="main-header">
			<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
				<a class="navbar-brand" href="{% url 'index' %}">지르미</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse"
				data-target="#navbarText" aria-controls="navbarText"
				aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
				<div class="collapse navbar-collapse" id="navbarText">
					<ul class="navbar-nav mr-auto">
						<li class="home-nav nav-item">
							<a class="nav-link" href="{% url 'index' %}">Home</a>
						</li>
						<li class="reviews-nav nav-item">
							<a class="nav-link" href="{% url 'reviews:review-list' %}">Reviews</a>
						</li>
						<li class="items-nav nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								My items
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
								<a class="dropdown-item" href="{% url 'items:my-item-list' %}">지르미들</a>
								<a class="dropdown-item" href="{% url 'items:my-complete-item-list' %}">완료된 지르미들</a>
							</div>

						</li>
					</ul>
					<ul class="navbar-nav ml-auto">
						{% if user.is_authenticated %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink2"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fas fa-user"></i> {{ user.email }}
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
									<a class="dropdown-item" href="{% url 'members:logout' %}"><i class="fas fa-sign-out-alt"></i> Sign Out</a>
								</div>
							</li>
						{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'members:login' %}"><i class="fas fa-sign-in-alt"></i> Sign in</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'members:signup' %}"><i class="fas fa-user"></i> Sign Up</a>
							</li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

	{% block content %} {% endblock %}

	{% include 'footer.html' %}




<script type="text/javascript">
	// nav-bar active 표시
	var page_path = window.location.pathname;
	var page_url = window.location.href;
	var path_regex = /items[/]\d+/;
	if (page_path == "/" || page_url.indexOf("items/public") != -1) {
		$(".home-nav").addClass("active");
	} else if (page_url.indexOf("reviews") != -1) {
		$(".reviews-nav").addClass("active");
	} else if (page_url.indexOf("items/list") != -1 || page_url.indexOf("items/complete") != -1 || page_url.indexOf("items/search") != -1 || path_regex.test(page_url)) {
		$(".items-nav").addClass("active");
	}



	$(window).scroll(function () {
		var offset = $(document).scrollTop();
		if (offset < 100) {
			$('.navbar').css('opacity', (1 - offset / 20));
		} else if (offset > 500){
			$('.navbar').css('opacity', (offset / 600));
		};
	})


</script>

</body>

</html>

app/templates/footer.html
<footer class="py-5 bg-dark">
  <div class="footer-container">
    <p class="m-0 text-center text-white">Copyright © zirmi 2018</p>
  </div>
</footer>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% load check_item_exists_tag %}
{% load date_formatter_tag %}

{% block content %}
<div class="top-container container">
  <a href="/"><h3>전체 지르미들</h3></a>
  <form action="" method="get" class="filter-form">
    <div class="filter-field-container">
      <div class="form-group">
        <label class="font-weight-bold">카테고리</label>
        <div class="">
          {% render_field filter.form.category class="custom-select" %}
        </div>
      </div>
    </div>
    <div class="filter-field-container">
      <div class="form-group">
        <label class="font-weight-bold">세대</label>
        <div class="">
          {% render_field filter.form.user__generation class="custom-select" %}
        </div>
      </div>
    </div>
    <div class="filter-field-container">
      <div class="form-group">
        <label class="font-weight-bold">성별</label>
        <div class="">
          {% render_field filter.form.user__gender class="custom-select" %}
        </div>
      </div>
    </div>
  </form>
</div>

<div id="item-container" class="album py-5 bg-light">
  <div class="container body-container">
    <div class="row">
      {% if not filter.qs %}
        <div class="empty-item">
          <p class="text-muted text-center">아이템이 없습니다</p>
        </div>
      {% endif %}
    {% for item in filter.qs %}
      <div id="item-{{ item.pk }}" class="custom-card-col">
          <div class="card mb-4 box-shadow align-items-center">
            <a href="{% url 'items:public-item-detail' item_pk=item.pk %}">
              <div class="card-button align-items-center">
                <img class="card-img-top"
                src="{% if item.img %}{{ item.img.url }}{% else %}{% static 'images/default_img.jpg' %}{% endif %}"
                alt="item-image">
                <span class="price-text">{{ item.price|intcomma }} 원</span>
                <p class="card-text text-center">{{ item.name }}</p>
              </div>
            </a>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if request.user.is_authenticated %}
                    {% check_item_exists item request as is_exists %}
                    {% if is_exists %}
                      <span class="btn btn-sm btn-outline-secondary disabled">이미 있음</span>
                    {% else %}
                      <button id="addItem-{{ item.pk }}" class="add-btn btn btn-sm btn-outline-secondary" name="{{ item.pk }}">내 지르미에 추가</button>
                    {% endif %}
                  {% endif %}
                  {% if request.user in item.like_users.all %}
                    <button class="like btn btn-sm btn-outline-secondary" name="{{ item.pk }}">
                      <i id="like-{{ item.pk }}" class="fas fa-heart"></i>
                    </button>
                  {% else %}
                    <button class="like btn btn-sm btn-outline-secondary" name="{{ item.pk }}">
                      <i id="dislike-{{ item.pk }}" class="far fa-heart"></i>
                    </button>
                  {% endif %}
                </div>
                {% with total_like=item.like_users.count %}
                <small id="count-{{ item.pk }}"class="text-muted">{{ total_like }} like{% if total_like == 0 %}{% else %}{{ total_like|pluralize }}{% endif %}</small>
                {% endwith %}
              </div>
            </div>
          </div>
      </div>
    {% endfor %}

    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).on("click", ".like", function() {
    var pk = $(this).attr('name')
    $.ajax({
      type: "POST",
      url: "{% url 'items:item-like-toggle' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",

      success: function(response) {
        $("#count-"+pk).text(response.like_count_text);
        if(response.message == '좋아요'){
          $("#dislike-"+pk).removeClass('far').addClass('fas');
        }else{
          $("#like-"+pk).removeClass('fas').addClass('far');
        }
      },
      error: function(request, status, error) {
        alert("로그인이 필요합니다")
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })

  $(document).on("click", ".add-btn", function() {
    var pk = $(this).attr('name')
    $.ajax({
      type: "POST",
      url: "{% url 'items:add-from-public' %}",
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
      dataType: "json",
      success: function(response) {
        alert(response.message)
        $("#addItem-"+pk).text("이미 있음")
        $("#addItem-"+pk).addClass('disabled')
      },
      error: function(request, status, error) {
        console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
    });
  })

  $('#id_category, #id_user__generation, #id_user__gender').change(function() {
    var categoryValue = $("#id_category").val();
    var generationValue = $("#id_user__generation").val();
    var genderValue = $("#id_user__gender").val();

    if (categoryValue && !generationValue && !genderValue) {
      var url = "?category="+categoryValue;
    } else if (categoryValue && generationValue && !genderValue) {
      var url = "?category="+categoryValue+"&user__generation="+generationValue;
    } else if (categoryValue && generationValue && genderValue) {
      var url = "?category="+categoryValue+"&user__generation="+generationValue+"&user__gender="+genderValue;
    } else if (!categoryValue && generationValue && !genderValue) {
      var url = "?user__generation="+generationValue;
    } else if (!categoryValue && generationValue && genderValue) {
      var url = "?user__generation="+generationValue+"&user__gender="+genderValue;
    } else if (!categoryValue && !generationValue && genderValue) {
      var url = "?user__gender="+genderValue;
    } else if (categoryValue && !generationValue && genderValue) {
      var url = "?category="+categoryValue+"&user__gender="+genderValue;
    } else {
      var url = "/";
    }
    window.location.replace(url);
  })


</script>




{% endblock %}